### ISSUE TITLE
Unable to see user app

### ISSUE THREAD

**Issue by Stomatic** [flxapps/DetoxDroid#55]
After the last app update I can't see the user apps in "manage exceptions..." anymore.
Besides that the Automatic Grayscale feature has stopped working, probably the problem is related to the one above.
I'm using graphene OS.

**Comment by vimalamp** [comment]
Same here.  I think it is related to:
`$ adb shell dpm set-device-owner com.flx_apps.digitaldetox/.DetoxDroidDeviceAdminReceiver

Exception occurred while executing 'set-device-owner':
java.lang.IllegalStateException: Not allowed to set the device owner because there are already some accounts on the device.
	at com.android.server.devicepolicy.DevicePolicyManagerService.enforceCanSetDeviceOwnerLocked(DevicePolicyManagerService.java:9410)
	at com.android.server.devicepolicy.DevicePolicyManagerService.setDeviceOwner(DevicePolicyManagerService.java:8353)
	at com.android.server.devicepolicy.DevicePolicyManagerServiceShellCommand.runSetDeviceOwner(DevicePolicyManagerServiceShellCommand.java:256)
	at com.android.server.devicepolicy.DevicePolicyManagerServiceShellCommand.onCommand(DevicePolicyManagerServiceShellCommand.java:89)
	at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
	at android.os.ShellCommand.exec(ShellCommand.java:38)
	at com.android.server.devicepolicy.DevicePolicyManagerService.onShellCommand(DevicePolicyManagerService.java:9729)
	at android.os.Binder.shellCommand(Binder.java:950)
	at android.os.Binder.onTransact(Binder.java:834)
	at android.app.admin.IDevicePolicyManager$Stub.onTransact(IDevicePolicyManager.java:6964)
	at android.os.Binder.execTransactInternal(Binder.java:1184)
	at android.os.Binder.execTransact(Binder.java:1143)
`

**Comment by vimalamp** [comment]
Also the quick title is grayed out

**Comment by vimalamp** [comment]
I have tried to manually enable the device admin for detox. It does not help though.

**Comment by Stomatic** [comment]
After the update still can't see the user apps in "manage exceptions..." other than detoxdroid

**Comment by smartlitchi** [comment]
It has been fixed with pull request #63. Now available as version 1.2.2
