### ISSUE TITLE
App crashes with NullPointerException when opening certain apps.

### ISSUE THREAD

**Issue by baschi29** [flxapps/DetoxDroid#56]
Happens for me for example with the Infusion Tea Timer from fdroid.

Android 11,  Detox Droid 1.2.0

Stack trace:
```
FATAL EXCEPTION: main
Process: com.flx_apps.digitaldetox, PID: 14905
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Object.hashCode()' on a null object reference
	at com.flx_apps.digitaldetox.DetoxAccessibilityService.handleScrollEvent(DetoxAccessibilityService.kt:160)
	at com.flx_apps.digitaldetox.DetoxAccessibilityService.onAccessibilityEvent(DetoxAccessibilityService.kt:104)
	at android.accessibilityservice.AccessibilityService$2.onAccessibilityEvent(AccessibilityService.java:2081)
	at android.accessibilityservice.AccessibilityService$IAccessibilityServiceClientWrapper.executeMessage(AccessibilityService.java:2284)
	at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:44)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:8010)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
```

**Comment by flxapps** [comment]
Should be fixed with v1.2.1. Thanks for reporting!
