### ISSUE TITLE
Uninstall app after giving admin owner

### ISSUE THREAD

**Issue by XPnJt8s7** [flxapps/DetoxDroid#65]
When trying to uninstall the app, the system marks it as unsuccessful. When trying to deactivate its admin ownership, the system simply gray out the "Deactivate" button. Also if removing from shell, this is what happens:

```
./adb shell dpm remove-active-admin com.flx_apps.digitaldetox/.DetoxDroidDeviceAdminReceiver                                                                                                   

Exception occurred while executing 'remove-active-admin':
java.lang.SecurityException: Attempt to remove non-test admin ComponentInfo{com.flx_apps.digitaldetox/com.flx_apps.digitaldetox.DetoxDroidDeviceAdminReceiver} 0
        at com.android.server.devicepolicy.DevicePolicyManagerService.lambda$forceRemoveActiveAdmin$9$DevicePolicyManagerService(DevicePolicyManagerService.java:4167)
        at com.android.server.devicepolicy.DevicePolicyManagerService$$ExternalSyntheticLambda21.runOrThrow(Unknown Source:6)
        at android.os.Binder.withCleanCallingIdentity(Binder.java:416)
        at com.android.server.devicepolicy.DevicePolicyManagerService$Injector.binderWithCleanCallingIdentity(DevicePolicyManagerService.java:1664)
        at com.android.server.devicepolicy.DevicePolicyManagerService.forceRemoveActiveAdmin(DevicePolicyManagerService.java:4163)
        at com.android.server.devicepolicy.DevicePolicyManagerServiceShellCommand.runRemoveActiveAdmin(DevicePolicyManagerServiceShellCommand.java:276)
        at com.android.server.devicepolicy.DevicePolicyManagerServiceShellCommand.onCommand(DevicePolicyManagerServiceShellCommand.java:93)
        at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
        at android.os.ShellCommand.exec(ShellCommand.java:38)
        at com.android.server.devicepolicy.DevicePolicyManagerService.onShellCommand(DevicePolicyManagerService.java:10698)
        at android.os.Binder.shellCommand(Binder.java:986)
        at android.os.Binder.onTransact(Binder.java:860)
        at android.app.admin.IDevicePolicyManager$Stub.onTransact(IDevicePolicyManager.java:7615)
        at android.os.Binder.execTransactInternal(Binder.java:1220)
        at android.os.Binder.execTransact(Binder.java:1179)
```

**Comment by XPnJt8s7** [comment]
In the menu, a new button appears to uninstall the app when the ownership is granted. I did not see it at first. This uninstall the app, but leaves the grayscale color on.
