### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by rajarshikhatua100** [flxapps/DetoxDroid#71]
FATAL EXCEPTION: pool-3-thread-1
Process: com.flx_apps.digitaldetox, PID: 19798
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.CharSequence android.content.Context.getText(int)' on a null object reference
	at android.content.pm.ApplicationInfo.getCategoryTitle(ApplicationInfo.java:1353)
	at com.flx_apps.digitaldetox.AppExceptionsListFragment.loadApps(AppExceptionsListFragment.kt:91)
	at com.flx_apps.digitaldetox.AppExceptionsListFragment_.access$101(AppExceptionsListFragment_.java:31)
	at com.flx_apps.digitaldetox.AppExceptionsListFragment_$2.execute(AppExceptionsListFragment_.java:150)
	at org.androidannotations.api.BackgroundExecutor$Task.run(BackgroundExecutor.java:400)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)

**Comment by jweickm** [comment]
This should be common sense, but maybe you could give some more information, like:
- What did you TRY TO ACHIEVE when you encountered this message?
- What did you DO when you encountered this message?
- Where did you observe this message?
- What model are you using?

**Comment by rajarshikhatua100** [comment]
> This should be common sense, but maybe you could give some more information, like:
> - What did you TRY TO ACHIEVE when you encountered this message?
> - What did you DO when you encountered this message?
> - Where did you observe this message?
> - What model are you using?

I just opened the app, i saw this message in Scoop app, I am using Samsung galaxy m31 (android 12)
